/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.3.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
    maven { url = uri("https://repo.codemc.io/repository/maven-releases/") }
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    compileOnly("org.spigotmc:spigot-api:1.20.2-R0.1-SNAPSHOT") // The Spigot API with no shadowing. Requires the OSS repo.ű
    implementation("net.kyori:adventure-api:4.26.1")
    implementation("net.kyori:adventure-platform-bukkit:4.4.1")
    implementation("net.kyori:adventure-text-serializer-legacy:4.26.1")
     compileOnly("com.github.retrooper:packetevents-spigot:2.11.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dragonanticheat.App"
}



