/*
 * This source file was generated by the Gradle 'init' task
 */
package ac.dragon;

import ac.dragon.checks.autoclicker.AutoClickerA;
import ac.dragon.config.ConfigManager;
import ac.dragon.ecs.EcsManager;
import ac.dragon.ecs.systems.CheckSystem;
import ac.dragon.ecs.systems.ClickSystem;
import ac.dragon.ecs.systems.JoinSystem;
import ac.dragon.ecs.systems.MovementSystem;
import io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder;
import net.kyori.adventure.platform.bukkit.BukkitAudiences;

import java.util.HashMap;
import java.util.UUID;

import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;
import org.checkerframework.checker.nullness.qual.NonNull;

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.event.PacketListenerPriority;

public class DragonAnticheat extends JavaPlugin {

    private static Plugin plugin;
    private static ConfigManager configManager;
    private final static HashMap<UUID, Integer> ID_MAP = new HashMap<>();
    private static BukkitAudiences adventure;

    public static String BANNER = """
                %c%
                ______  ______   _______ _______ _______ __    _
               |      ||    _ | |   _   |       |       |  |  | |
               |  _    |   | || |  |_|  |    ___|   _   |   |_| |
               | | |   |   |_||_|       |   | __|  | |  |       |
               | |_|   |    __  |       |   ||  |  |_|  |  _    |
               |       |   |  | |   _   |   |_| |       | | |   |
               |______||___|  |_|__| |__|_______|_______|_|  |__|

            Hooked into PacketEvents | Using API version: Spigot %v% %r%
            """;

    @Override
    public void onLoad() {
        // Building, loading, and initializing the library is necessary when bundling.
        PacketEvents.setAPI(SpigotPacketEventsBuilder.build(this));
        PacketEvents.getAPI().load();

        /*
         * MORE CODE MAY APPEAR HERE (such as registering listeners)
         */
    }

    @NonNull
    public static BukkitAudiences adventure() {
        if (adventure == null) {
            throw new IllegalStateException("Tried to access Adventure when the plugin was disabled!");
        }
        return adventure;
    }

    @Override
    public void onEnable() {
        saveDefaultConfig();
        plugin = this;
        configManager = new ConfigManager(getConfig());
        getLogger().info(
                BANNER.replace("%v%", getServer().getBukkitVersion())
                        .replace("%c%", "\u001B[35m")
                        .replace("%r%", "\u001B[0m"));
        this.adventure = BukkitAudiences.create(this);
        initEcs();

        // Initialize the library!
        PacketEvents.getAPI().init();
    }

    public void initEcs() {
        getServer().getPluginManager().registerEvents(new JoinSystem(), this);
        PacketEvents.getAPI().getEventManager().registerListener(new ClickSystem(), PacketListenerPriority.NORMAL);
        
        PacketEvents.getAPI().getEventManager().registerListener(new MovementSystem(), PacketListenerPriority.NORMAL);
        PacketEvents.getAPI().getEventManager().registerListener(new CheckSystem(), PacketListenerPriority.NORMAL);
        getLogger().info("Initializing the Check system...");
    }

    @Override
    public void onDisable() {
        PacketEvents.getAPI().terminate();
    }

    public static Plugin getPlugin() {
        return plugin;
    }

    public static ConfigManager getConfigManager() {
        return configManager;
    }

    public static HashMap<UUID, Integer> getIdMap() {
        return ID_MAP;
    }

    public static BukkitAudiences gBukkitAudiences() {
        return adventure;
    }
}
